site_name: AutoNN

theme:
  logo : img/ico.png  
  favicon : img/ico.png  
  name: material
  features:
    - content.code.annotate 
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.tabs
    - navigation.expand
    - toc.follow
    # - toc.integrate 

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/AutoNN/AutoNN
site_url: https://autonn.github.io/AutoNN/

site_description: 'Documentation for AutoNN'

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search

nav:
  - Installation & Intro: "index.md"
  - Documentation:
    - class CNN : "documentation/cnn1.md"
    - class CreateCNN : "documentation/cnn2.md"
    - CNN.codeBlocks : "documentation/cnn3.md"
    - class Augment : "documentation/utils1.md"
    - def resnet : "documentation/resnet.md"
    # - day : "documentation/doc.md"
    # - Preprocess : "documentation/preprocess1.md"
  - Tutorial: 
    - Image Classification: "tutorial/tut.md"
    - Handle Tabular Dataset: "tutorial/tut1.md"
  - GUI:
    - For Tabular Dataset: "gui/lesson1.md"
    - For Image Dataset: "gui/lesson2.md"
  - About: "about.md"


extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
