site_name: AutoNN

theme:
  logo : img/ico.png  
  favicon : img/icon.png  
  name: material
  features:
    - content.code.annotate 
  palette:
      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/AutoNN/AutoNN
site_url: ""

site_description: 'Documentation for AutoNN'

markdown_extensions:
  - attr_list
  - md_in_html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Installation & Intro: "index.md"
  - Documentation:
    - class CNN() : "documentation/cnn1.md"
  - Tutorial: 
    - Image Classification: "tutorial/tut.md"
    - Handle Tabular Dataset: "tutorial/tut1.md"
  - GUI:
    - For Tabular Dataset: "gui/lesson1.md"
    - For Image Dataset: "gui/lesson2.md"
  - About: "about.md"