
name: Upload Python Package

on:
  release:
    types: [created]
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
    - name: Build package

      run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
      env:
          TWINE_USERNAME: Gsauce
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}